default_stages: [pre-commit, pre-push]
fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
    exclude: "internal/ipcountry/GeoLite2-Country.mmdb|internal/httpapi/customer/customerapi.html"
  - id: fix-byte-order-marker
  - id: check-symlinks
  - id: detect-private-key
    exclude: 'internal/temporalw/activities/txrecon/testdata/ssh_host_ed25519_key|internal/ioeater/resource/testdata/ssh_host_ed25519_key|internal/extpartner/dfns/testdata/privatekey'
  - id: check-yaml
  - id: check-json
  - id: check-toml
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.0.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
    args: ['--baseline', '.secrets.baseline', '--base64-limit', '6']
    exclude: '.*\.gen\.go$|internal/temporalw/activities/txrecon/testdata/ssh_host_ed25519_key|internal/ioeater/resource/testdata/ssh_host_ed25519_key|internal/extpartner/dfns/testdata/privatekey'
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: no-go-testing
    - id: golangci-lint
      args: [--config=./.golangci.toml]
      stages: [pre-push]
    - id: go-mod-tidy
    - id: go-generate
      args: [./...]
    - id: go-build
      stages: [pre-push]
- repo: local
  hooks:
  - id: go-tests
    name: go-tests
    entry: |
      sh -c 'set -o pipefail; make test | tee /dev/stderr | grep -q FAIL && exit 1 || exit 0'
    language: system
    stages: [pre-push]
