services:
  - type: web
    plan: starter
    region: singapore
    name: realworld-sgp
    runtime: image
    image:
      url: ghcr.io/vincentserpoul/realworld-go-oapi-codegen-chi-pgx:v0.0.26
    healthCheckPath: /sys/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: renderworld-sgp
          property: connectionString
      - key: ENV
        value: prod
databases:
  - name: renderworld-sgp
    region: singapore
