services:
  - type: web
    plan: starter
    name: realworld
    region: singapore
    runtime: image
    image:
      url: ghcr.io/vincentserpoul/realworld-go-oapi-codegen-chi-pgx:v0.0.15
    healthCheckPath: /sys/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: renderworld
          property: connectionString
      - key: ENV
        value: prod
databases:
  - name: renderworld
    region: singapore
