version: '3'
services:
  # postgres
  lp-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localworld
      POSTGRES_DB: realworld
    ports:
      - '5432:5432'
  # openobserve
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.7.2
    restart: always
    ports:
      - '5080:5080'
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      ZO_DATA_DIR: /data
      ZO_ROOT_USER_EMAIL: test@po.com
      ZO_ROOT_USER_PASSWORD: test # pragma: allowlist secret
