version: '3'
services:
  # postgres
  lp-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localworld
      POSTGRES_DB: realworld
    ports:
      - '5432:5432'
  jaegertracing-all-in-one:
    image: jaegertracing/all-in-one:1.51
    restart: always
    ports:
      - '14250:14250'
      - '16686:16686'
      - '4317:4317'
