apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ./service.yaml
  - ./namespace.yaml
  - ./ingress.yaml

namespace: reference

patchesStrategicMerge:
  - deployment.yaml
