name = "realworld-go-std-sqlc-postgres-api"

version = "v1"
with_debug_profiler = false

[log]
is_pretty = false
level = "error"

[observability.collector]
host = "otlp.nr-data.net"
port = 4_317
is_secure = true
enable_metrics = true

[http]
port = 8_083
health_endpoint = "/sys/health"
