name = "realworld-go-oapi-codegen-chi-pgx"

version = "v1"
with_debug_profiler = false

secrets_path = "config/api/base.secrets.toml" # pragma: allowlist secret

[log]
is_pretty = false
level = "error"

[observability.collector]
host = "localhost"
port = 4_317

[http]
port = 8_083
health_endpoint = "/sys/health"
