# this config is for your local environment
with_debug_profiler = true
database_url = "postgres://postgres:localworld@localhost:5432/realworld?sslmode=disable"
env = "local"

[log]
is_pretty = true
level = "debug"

[observability.collector]
host = "127.0.0.1"
is_secure = false
enable_metrics = false

[security]
jwt_secret = "secret"
