# this config is for your local environment
with_debug_profiler = true
env = "local"

secrets_path = "config/api/local.secrets.toml" # pragma: allowlist secret

[log]
is_pretty = true
level = "debug"

[observability.collector]
host = "127.0.0.1"
port = 5_080
is_insecure = true
with_metrics_enabled = false
