database_url = "postgres://postgres:localworld@localhost:5432/realworld?sslmode=disable" # pragma: allowlist secret

[security]
jwt_secret = "secret" # pragma: allowlist secret

[[observability.collector.headers]]
key = "Authorization"
value = "Basic xxx"   # pragma: allowlist secret
